config/routes.rb
Landingpage::Application.routes.draw do

  get "blocks/index"

  match "login"=>"users#login"
  match "logout"=>"users#logout"
  match "denied"=> "users#denied"
  match "pages/duplicate" => "pages#duplicate"
  match "ads/index" => "ads#index"
  match "ads/duplicate" => "ads#duplicate"
  match "page/elfinder" => "page#elfinder"
  match "blocks/index" => "blocks#index"
  match "blocsk/new"=>"blocks#new"

  resources :users
  resources :privileges
  resources :pages
  resources :ads
  resources :blocks








   root :to => 'users#index'


  match ':controller(/:action(/:id))(.:format)'
end

app/models/ad.rb
class Ad < ActiveRecord::Base
  #attr_accessible :pageId, :name, :order,:hasContactButton, :active
  attr_protected
  def self.getAdsesByPageId(pageId)
    @ad = Ad.where('"pageId"=?', pageId)
    return @ad
  end
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  def index
    @pageId = params[:pageId]
    @pageId = Integer(@pageId)
    @page = Page.getPage(@pageId)
    @page= Page.find(@page[0].id)
    @pages = Page.viewList('','','')
    @ads = Ad.getAdsesByPageId(@pageId)

  end
  def  new
    @ad = Ad.new
    @listPages = Page.all
    @listLanguages = Language.all
    @pageId = params[:pageId]
    @page = Page.find(@pageId)
  end
  def create
    @paramsAd = {"pageId"=>params[:ad]["pageId"],"name"=>params[:ad]["name"],"hasContactButton"=>params[:ad]["hasContactButton"],"active"=>params[:ad]["active"]  }

    @ad = Ad.new(@paramsAd)
    @ad.save
    @ad_contents = params[:ad]["ad_contents"]
    @paramsAdContent = {"adsId"=>@ad.id,"ad1Content"=>@ad_contents["ad1Content"],"popupContent"=>@ad_contents["popupContent"],"cbExplanationText"=>@ad_contents["cbExplanationText"],
                        "cbPrefilledText"=>@ad_contents["cbPrefilledText"],"cbTargetEmail"=>@ad_contents["cbTargetEmail"],"cbButtonName"=>@ad_contents["cbButtonName"],"languageCode"=>params[:ad]["languageCode"]}
    @adContent = AdContent.new(@paramsAdContent)
    @adContent.save
    redirect_to  :controller=>"ads",:action=>"index", :pageId=>params[:ad]["pageId"]
  end
  def edit
    @adId = params[:id]
    @a=Ad.select('ads.*,ad_contents.id as id1,ad_contents."adsId",ad_contents."ad1Content",ad_contents."popupContent",ad_contents."cbExplanationText",ad_contents."cbPrefilledText",ad_contents."cbTargetEmail",ad_contents."cbButtonName",ad_contents."languageCode"').
        joins('LEFT JOIN ad_contents ON ads.id = ad_contents."adsId"').where("ads.id=?",@adId)
    @ad = @a.find(@adId)
    @listPages = Page.all
    @listLanguages = Language.all
    @listUser = User.all
  end
  def update
    @ad = Ad.find(params[:id])

    @paramsAd = {"pageId"=>params[:ad]["pageId"],"name"=>params[:ad]["name"],"hasContactButton"=>params[:ad]["hasContactButton"],"active"=>params[:ad]["active"]  }
    if  params[:ad]["id1"]==''
      @paramsAdContent = {"adsId"=>@ad.id,"ad1Content"=>params[:ad]["ad1Content"],"popupContent"=>params[:ad]["popupContent"],"cbExplanationText"=>params[:ad]["cbExplanationText"],"cbPrefilledText"=>params[:ad]["cbPrefilledText"],"cbTargetEmail"=>params[:ad]["cbTargetEmail"],"cbButtonName"=>params[:ad]["cbButtonName"],"languageCode"=>params[:ad]["languageCode"]}
      @adContent = AdContent.new(@paramsAdContent)
      @adContent.save
    else
      @paramsAdContent = {"ad1Content"=>params[:ad]["ad1Content"],"popupContent"=>params[:ad]["popupContent"],"cbExplanationText"=>params[:ad]["cbExplanationText"],"cbPrefilledText"=>params[:ad]["cbPrefilledText"],"cbTargetEmail"=>params[:ad]["cbTargetEmail"],"cbButtonName"=>params[:ad]["cbButtonName"],"languageCode"=>params[:ad]["languageCode"]}
      @id = Integer(params[:ad]["id1"])
      @adContent = AdContent.find(@id)
      @adContent.update_attributes(@paramsAdContent)
    end
    @ad.update_attributes(@paramsAd)
    redirect_to  :controller=>"ads",:action=>"index", :id=>@ad.pageId

  end
  def duplicate
    @ad = Ad.find(params[:id])
    @adCopy = @ad.dup     # dup: duplicate
    @adCopy.name = @adCopy.name +  "-Copy"
    @adCopy.save
    redirect_to :back
  end
  def destroy
    @ad = Ad.find(params[:id])
    @ad.destroy
    redirect_to :back
  end
end

app/views/ads/edit.html.erb
<div id="ads_form">
  <h2>Add new Ads</h2>
  <p>
    <%= link_to " Ads management", ads_path %>
    ><%= @ad.name %></a>
  </p>
  <div class="formads">
    <%= form_for :ad, :url=>ad_path(@ad.id), :method=>"put"   do |f| %>
		<span class="adsspan">
                <%= f.label :pageId, "Choose landing page" %>
                <%= select_tag 'ad[pageId]',  options_from_collection_for_select(@listPages, 'id', 'pageName', @ad.pageId) ,:class=>"selectbox required",:name=>'ad[pageId]' %>
			</span>
		<span class="adsspan">
			<%=f.label :name ,"Name" %>
          <%=f.text_field :name,:class=>"inputbox required" %>
		</span>
		<span class="adsspan">
			<%=f.label :hasContactButton ,"Contact Button"%>
          <%=f.check_box :hasContactButton %>
          <input type="hidden" value="0" />
		</span>
		<span class="adsspan">
			<%=f.label :active,"Active" %>
          <%=f.check_box :active  %>
          <input type="hidden" value="0" />
		</span>

		<span class="adsspan">
		    <%=f.label :languageCode ,"Choose language" %>
            <%= select_tag 'ad[languageCode]',  options_from_collection_for_select(@listLanguages, 'languageCode', 'languageName', @ad.languageCode) ,:class=>"selectbox",:name=>'ad[languageCode]' %>
		</span>
        <div class="editor">
          <%=f.label :ad1Content, "Ads Content" %>
          <div class="editor_container">
            <%=f.text_area :ad1Content,:class=>"textbox ckeditor" %>
          </div>
			<span class="preview" style="line-height:40px;" onMouseOver="loadPreviewAds();">&nbsp;Preview
				<span id="previewAdsContent" class="adscontentpreview"></span>
			</span>
        </div>
        <div class="editor">
          <%=f.label :popupContent,"Popup Content" %>
          <div class="editor_container">
            <%=f.text_area :popupContent,:class=>"textbox ckeditor" %>
          </div>
			<span class="preview" style="line-height:40px;" onMouseOver="loadPopupContent();">&nbsp;Preview
				<span id="previewPopupContent" class="popupcontentpreview"></span>
			</span>
        </div>
		<span class="adsspan">
			<%=f.label :cbExplanationText, "Explanation Text" %>
          <%=f.text_field :cbExplanationText ,:class=>"inputbox" %>
		</span>
		<span class="adsspan">
			<%=f.label :cbPrefilledText, "Prefilled Text" %>
          <%=f.text_field :cbPrefilledText ,:class=>"inputbox" %>
		</span>
		<span class="adsspan">
			<%=f.label :cbTargetEmail, "Target Email" %>
          <%=f.text_field :cbTargetEmail ,:class=>"inputbox" %>
		</span>
		<span class="adsspan">
			<%=f.label :cbButtonName, "Button Name" %>
          <%=f.text_field :cbButtonName ,:class=>"inputbox" %>
		</span>

		<span class="adsspan">
		    <label>&nbsp;</label>
            <input type="hidden" name="ad[id1]" value="<%= @ad.id1 %>">
            <%= f.submit :value=>"Save", :class=>"button" %>
		</span>
    <% end %>
  </div>

</div>


app/views/ads/index.html.erb
<div id="user_list">
  <h2>Ads Management</h2>
  <p>
    <%= link_to "Landing page list", pages_path %>
    ><%= link_to @page.pageName, edit_page_path(@page.id) %></a>
    > Ads management
  </p>
  <%= link_to "+ Add new Ads" ,:controller=>"ads",:action=>"new",:pageId=>@page.id %>
	<span class="adsspan" style="float:right;">
      <%= form_for :page, :id=>"ads_form",:class=>"dataForm",:controller=>"ads",:action=>"index", :id=>15 do |f|%>
        <%= select_tag 'page[pageSelect][]',  options_from_collection_for_select(@pages, 'id', 'pageName',@page.id),:class=>"pageSelect selectbox" %>
      <% end %>
	</span>
  <table class="list" cellpadding="0" cellspacing="0">
    <thead>
    <tr>
      <td width="5%">Id</td>
      <td>Name</td>
      <td width="20%">Landing Page Name</td>
      <td width="8%">Order</td>
      <td width="8%">Active</td>
      <td width="22%">Actions</td>
    </tr>
    </thead>
    <tbody>
    <% @ads.each do |row| %>
    <% if row.active==1
        @Status = "Active"
       else
        @Status = "Hidden"
       end
    %>
    <tr>
        <td><%= row.id %></td>
        <td><%= row.name %></td>
        <td title="<?php if($changeName) echo $pageName;?>">
          <?php if($changeName) echo $newName; else echo $pageName ;?>
          <%= @page.pageName %>
        </td>
        <td>
          <a class="narrow_down" title="Move down" href="#">
            <img src="/assets/images/ico_move_down.png" border="0">
          </a>
          <a class="narrow_up" title="Move up" href="#">
            <img src="/assets/images/ico_move_up.png" border="0">
          </a>
        </td>
        <td><%= @Status %></td>
        <td>
          <%= link_to "Duplicate",:action=>"duplicate",:id=>row %>
          <%= link_to "Edit", edit_ad_path(row)%>
          <%=  link_to 'Delete', ad_path(row),:method=>"delete", :data=>{ :confirm=>'Are you sure?' } %>
        </td>
    </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/ads/new.html.erb
<?php
// no direct access
defined( '_HEXEC' ) or die( 'Access error' );
?>
<?php
$msg = $this->msg;
$arrLanguages = $this->arrLanguages;
$languageSelected = $this->languageCode;

$arrPages = $this->arrPages;
$pageId = $this->pageId;

$arrNames = array();
for($i = 0; $i< count($arrPages); $i ++) {
//echo $arrPages[$i]['id'].'-'.$arrPages[$i]['pageName'].'<br>';
$arrNames[$arrPages[$i]['id']] = $arrPages[$i]['pageName'];
}
?>
<script language="JavaScript" type="text/javascript">
    function loadPreviewAds() {
        document.getElementById('previewAdsContent').innerHTML = CKEDITOR.instances.ad1Content.getData();
    }
    function loadPopupContent() {
        document.getElementById('previewPopupContent').innerHTML = CKEDITOR.instances.popupContent.getData();
    }
    function checkChooseLandingPage() {
        if(document.getElementById('pageSelect').value < 1) {
            alert("Please choose landing page");
            document.getElementById('pageSelect').focus();
            return false;
        }
        return true;
    }
</script>

<div id="ads_form">
  <h2>Add new Ads</h2>
  <p>
    <%= link_to "Landing page list", pages_path %>
    > <%= link_to @page.pageName ,edit_page_path(@page.id) %></a>
    > <%= link_to "Ads management",:controller=>"ads",:action=>"index",:pageId=>@page.id%>
    > Add new Ads
  </p>
  <div class="formads">
    <%= form_for :ad, :url=>ads_path, :method=>"post"   do |f| %>
    <form method="post" class="dataForm" action="index.php?c=ads&task=add" enctype="multipart/form-data" onSubmit="return checkChooseLandingPage();">
			<span class="adsspan">
                <%= f.label :pageId, "Choose landing page"%>
                <%= select_tag 'ad[pageId]',  options_from_collection_for_select(@listPages, 'id', 'pageName', @page.id) ,:class=>"selectbox required",:name=>'ad[pageId]' %>
			</span>
			<span class="adsspan">
                <%=f.label :name ,"Name" %>
                <%=f.text_field :name,:class=>"inputbox required" %>
			</span>
			<span class="adsspan">
                <%=f.label :hasContactButton ,"Contact Button"%>
                <%=f.check_box :hasContactButton,:value=>"1" %>
              <input type="hidden" value="0" />
			</span>
            <span class="adsspan">
                <%=f.label :active,"Active" %>
                <%=f.check_box :active, :value=>"1",:checked=>true %>
                <input type="hidden" value="0" />
			</span>
            <%= f.fields_for :ad_contents do |a| %>
			<span class="adsspan">
                <%= a.label :languageCode, "Choose language"%>
                <%= select_tag 'ad[languageCode]',  options_from_collection_for_select(@listLanguages, 'languageCode', 'languageName', '1') ,:class=>"selectbox",:name=>'ad[languageCode]' %>
			</span>
            <div class="editor">
                <%= a.label :ad1Content,"Ads Content" %>
            <div class="editor_container">
                <%= a.text_area :ad1Content,:class=>"textbox ckeditor" %>
            </div>
				<span class="preview" style="line-height:40px;" onMouseOver="loadPreviewAds();">&nbsp;Preview
					<span id="previewAdsContent" class="adscontentpreview"></span>
				</span>
            </div>
            <div class="editor">
                <%= a.label :popupContent, "Popup Content" %>
            <div class="editor_container">
                <%= a.text_area :popupContent,:class=>"textbox ckeditor" %>
            </div>
				<span class="preview" style="line-height:40px;" onMouseOver="loadPopupContent();">&nbsp;Preview
					<span id="previewPopupContent" class="popupcontentpreview"></span>
				</span>
            </div>
			<span class="adsspan">
				<label>Contact button</label>
			</span>
			<span class="adsspan">
                    <%= a.label :cbExplanationText, "Explanation Text" %>
                    <%= a.text_field :cbExplanationText, :class=>"inputbox"%>

			</span>
			<span class="adsspan">
                <%= a.label :cbPrefilledText ,"Prefilled Text" %>
                <%= a.text_field :cbPrefilledText, :class=>"inputbox"%>
			</span>
			<span class="adsspan">
                <%= a.label :cbTargetEmail ,"Target Email" %>
                <%= a.text_field :cbTargetEmail, :class=>"inputbox"%>
			</span>
			<span class="adsspan">
				<%= a.label :cbButtonName, "Button Name" %>
                <%= a.text_field :cbButtonName, :class=>"inputbox"%>
			</span>
            <% end %>
			<span class="adsspan">
				<label>&nbsp;</label>
                <%= f.submit :value=>"Save", :class=>"button" %>
			</span>
    <% end %>
  </div>

</div>
