config/routes.rb
Landingpage::Application.routes.draw do

  get "blocks/index"

  match "login"=>"users#login"
  match "logout"=>"users#logout"
  match "denied"=> "users#denied"
  match "pages/duplicate" => "pages#duplicate"
  match "ads/index" => "ads#index"
  match "ads/duplicate" => "ads#duplicate"
  match "page/elfinder" => "page#elfinder"
  match "blocks/index" => "blocks#index"
  match "blocsk/new"=>"blocks#new"

  resources :users
  resources :privileges
  resources :pages
  resources :ads
  resources :blocks








   root :to => 'users#index'


  match ':controller(/:action(/:id))(.:format)'
end

app/models/privilege.rb
class Privilege < ActiveRecord::Base
  attr_accessible :controller, :description, :privilege, :task
  
 def self.checkPrivilege _privilege, curentController,curentAction
   @listPrivilege = Privilege.where("controller = '#{curentController}' and task like '%#{curentAction}%' and privilege like '%#{_privilege}'")
   if(@listPrivilege.count > 0) 
     return @listPrivilege
   else 
     return false
    end
 end 
end
## 1,50,100
## 1

app/controllers/privileges_controller.rb
class PrivilegesController < ApplicationController
   before_filter :checkAuthentication , :only=>['index', 'new', 'edit','destroy']
  def index
    @privilege = Privilege.order(:controller).page(params[:page]).per(10)
  end

  def new
    #render :text=> controller_path()
    #return
    @privilege = Privilege.new
  end

  def create
    @privilege = Privilege.new(params[:privilege]) do |p|
      @pri = params[:privilege]["privilege"]
      @pri = @pri.split('-')
      @strPrivilege = ""
      @index = 0;
      @pri.each do |i|
        i.each do |j|
          @strPrivilege += j.to_str 
          if(i.count-1 > @index)
            @strPrivilege += ","
         end
          @index +=1
        end
        
      end
      p.privilege = @strPrivilege
    end
    
    if @privilege.save
      redirect_to :action=>"index"
    else
      render "new"
    end
  end
  def edit
    @privilege = Privilege.find(params[:id])
  end

  def update
    @privilege = Privilege.find(params[:id])
 
    @pri = params[:privilege]["privilege"]
      @pri = @pri.split('-')
      @strPrivilege = ""
      @index = 0;
      @pri.each do |i|
        i.each do |j|
          @strPrivilege += j.to_str 
          if(i.count-1 > @index)
            @strPrivilege += ","
         end
          @index +=1
        end
        
      end
      params[:privilege]["privilege"] = @strPrivilege
      
    if @privilege.update_attributes(params[:privilege])
      redirect_to :action=>"index"
    else
      render 'edit'
    end
  end
  
  def destroy
    @privilege = Privilege.find(params[:id])
    @privilege.destroy
   redirect_to privileges_path
  end
end

app/helpers/privileges_helper.rb
module PrivilegesHelper
end

app/views/privileges/destroy.html.erb
<h1>Privileges#destroy</h1>
<p>Find me in app/views/privileges/destroy.html.erb</p>

app/views/privileges/edit.html.erb
<div id="user_form" class="relative">
	<h2>Add new Privilege</h2>
	<p>
		<%= link_to "Privilege management", privileges_path()%>
		> Edit Privilege
    </p>
    <div class="form">
			<%= form_for :privilege, url: privilege_path(@privilege.id,'update'), :method=>"PUT" do |f|%>
			<span>
				<%= f.label :controller, "Controller"%>
				<%= f.text_field :controller, :class=>"inputbox required"%>
				 <span id="lblMsg" class="msg" style="color:red; margin-left: 10px;">
			</span>
			</span>
			
			<span>
				<%= f.label :task, "Task"%>
				<%= f.text_field :task, :class=>"inputbox required"%>
				 <span id="lblMsg" class="msg" style="color:red; margin-left: 10px;">
			</span>
			</span>
		
            <span>
				<%= f.label :privilege, "privilege"%>
				<%= select_tag "privilege[privilege]",  options_for_select([["APG",1],["SWAT Leader",50],["SWAT Team",100]],@privilege.privilege.split(',')), :multiple => true %>
           </span>
			<br />	
			<span>
				<%= f.label :description, "Description"%>
				<%= f.text_area :description,:class=>"textbox descript-privilege" %>
           </span>
           
			<span>
				<label>&nbsp;</label>
				<%= f.submit "Save", :disable_with => 'Save', :class=>"button"%>
			</span>
		<% end %>
    </div>
    
</div>

app/views/privileges/index.html.erb
<div id="user_list">
    <h2>Privilege Management</h2>
    <%= link_to "+ Add new Privilege", new_privilege_path()%>
    <table class="list" cellpadding="0" cellspacing="0">
        <thead>
            <tr>
                <td width="5%">Id</td>
                <td>Controller</td>
                <td>Task</td>
                <td width="12%">Actions</td>
            </tr>
        </thead>
        <tbody>
        	
			<% @privilege.each do |row|%>
			<tr>
                <td><%= row.id %></td>
                <td><%= row.controller %></td>
                <td><%= row.task%></td>
                <td>
                    <!-- <a href="index.php?c=user&task=edit&id=<?php echo $id;?>">Edit</a> -->
                    <%= link_to "Edit", edit_privilege_path(row.id)%>
                   <%= link_to 'Delete', privilege_path(row,"destroy"),:method=> :delete, :confirm => "Are you sure?" %>
                   </td>
            </tr>
            <% end%>
            
        </tbody>
    </table>
     <%= paginate @privilege %>
</div>

app/views/privileges/new.html.erb
<div id="user_form" class="relative">
	<h2>Add new Privilege</h2>
	<p>
		<%= link_to "Privilege management", privileges_path()%>
		> Add new Privilege
    </p>
    <div class="form">
			<%= form_for :privilege, url: privileges_path, :method=>"post" do |f|%>
			<span>
				<%= f.label :controller, "Controller"%>
				<%= f.text_field :controller, :class=>"inputbox required"%>
				 <span id="lblMsg" class="msg" style="color:red; margin-left: 10px;">
			</span>
			</span>
			
			<span>
				<%= f.label :task, "Task"%>
				<%= f.text_field :task, :class=>"inputbox required"%>
				 <span id="lblMsg" class="msg" style="color:red; margin-left: 10px;">
			</span>
			</span>
		
            <span>
				<%= f.label :privilege, "privilege"%>
				<%= select_tag "privilege[privilege]",  options_for_select([["APG",1],["SWAT Leader",50],["SWAT Team",100]]), :multiple => true %>
           </span>
			<br />	
			<span>
				<%= f.label :description, "Description"%>
				<%= f.text_area :description,:class=>"textbox descript-privilege" %>
           </span>
           
			<span>
				<label>&nbsp;</label>
				<%= f.submit "Save", :disable_with => 'Save', :class=>"button"%>
			</span>
			<input type="hidden" id="txtListUsername" value="" />
		<% end %>
    </div>
    
</div>