config/routes.rb
Landingpage::Application.routes.draw do

  get "blocks/index"

  match "login"=>"users#login"
  match "logout"=>"users#logout"
  match "denied"=> "users#denied"
  match "pages/duplicate" => "pages#duplicate"
  match "ads/index" => "ads#index"
  match "ads/duplicate" => "ads#duplicate"
  match "page/elfinder" => "page#elfinder"
  match "blocks/index" => "blocks#index"
  match "blocsk/new"=>"blocks#new"

  resources :users
  resources :privileges
  resources :pages
  resources :ads
  resources :blocks








   root :to => 'users#index'


  match ':controller(/:action(/:id))(.:format)'
end

app/models/block.rb
class Block < ActiveRecord::Base
  attr_accessible :pageId, :blockName,:isAlternative,:picture, :oder, :active
  def self.getBlocksByPageId(pageId)
    @block = Block.where('"pageId"=?', pageId)
    return @block
  end
end

app/controllers/blocks_controller.rb
class BlocksController < ApplicationController
  def index
    @pageId = params[:pageId]
    @pageId = Integer(@pageId)
    @page = Page.getPage(@pageId)
    @page= Page.find(@page[0].id)
    @blocks = Block.getBlocksByPageId(@pageId)
  end
  def new
    @pageId = params[:pageId]
    @page = Page.find(@pageId)
    @block = Block.new

  end
  #start function creat block
  def create
    @block = Block.new(params[:block])
    if @block.save
      redirect_to :controller=>"blocks",:action=>"index",:pageId=>params[:block]["pageId"]
    else
      render 'new'
    end
  end
  #end function creat block
  def edit
    @blockId = params[:id]
    @a=Block.select('blocks.*,block_contents.id as id1,block_contents."blockId",block_contents."section1",block_contents."section2",block_contents."section3",block_contents."section4",block_contents."quote1",block_contents."quote2",block_contents."quote3",block_contents."languageCode"').
        joins('LEFT JOIN block_contents ON blocks.id = block_contents."blockId"').where("blocks.id=?",@blockId)
    @block = @a.find(@blockId)
    @page =Page.where("id=?",@block.pageId)
    @listLanguages = Language.all
    @listIcons =Icon.all
  end
  #start function update block
  def update
    @block = Block.find(params[:id])

    @paramsBlock = {"pageId"=>params[:block]["pageId"],"blockName"=>params[:block]["blockName"],"isAlternative"=>params[:block]["isAlternative"],"picture"=>params[:block]["picture"],"active"=>params[:block]["active"]  }

    if  params[:block]["id1"]==''
      @paramsBlockContent = {"blockId"=>@block.id,"section1"=>params[:block]["section1"],"section2"=>params[:block]["section2"],"section3"=>params[:block]["section3"],"section4"=>params[:block]["section4"],"quote1"=>params[:block]["quote1"],"quote2"=>params[:block]["quote2"],"quote3"=>params[:block]["quote3"],"languageCode"=>params[:block]["languageCode"]}
      @blockContent = BlockContent.new(@paramsBlockContent)
      @blockContent.save
      @msg = 'Successfully saved  !'
    else
      @paramsBlockContent = {"section1"=>params[:block]["section1"],"section2"=>params[:block]["section2"],"section3"=>params[:block]["section3"],"section4"=>params[:block]["section4"],"quote1"=>params[:block]["quote1"],"quote2"=>params[:block]["quote2"],"quote3"=>params[:block]["quote3"],"languageCode"=>params[:block]["languageCode"]}
      @id = Integer(params[:block]["id1"])
      @blockContent = BlockContent.find(@id)
      @blockContent.update_attributes(@paramsBlockContent)
    end
    @block.update_attributes(@paramsBlock)
    redirect_to  :controller=>"blocks",:action=>"index", :pageId=>params[:block]["pageId"]

  end
  #end function update block
  def destroy
    @block = Block.find(params[:id])
    @block.destroy
    redirect_to :back
  end
end

app/helpers/block_helper.rb
module BlockHelper
end

app/views/blocks/index.html.erb
<div id="block_list">
  <h2>Blocks management</h2>
  <p>
    <%= link_to "Landing page list", pages_path %>
    ><%= link_to @page.pageName, edit_page_path(@page.id) %></a>
    > Blocks management
  </p>
  <%= link_to "+ Add new Block" ,:controller=>"blocks",:action=>"new",:pageId=>@page.id %>
  <table class="list" cellpadding="0" cellspacing="0">
    <thead>
    <tr>
      <td width="5%">Id</td>
      <td>Block Name</td>
      <td width="8%">Order</td>
      <!--<td width="10%">Is Alternative</td>-->
      <td width="8%">Status</td>
      <td width="18%">Actions</td>
    </tr>
    </thead>
    <tbody>
    <% @blocks.each do |row| %>
    <% if row.active==1
             @Status = "Active"
           else
             @Status = "Hidden"
           end
    %>
    <tr>
      <td><%= row.id %></td>
      <td><%= row.blockName %></td>
      <td>
        <a class="narrow_down" title="Move down" href="#">
          <img src="/assets/images/ico_move_down.png" border="0">
        </a>
        <a class="narrow_up" title="Move up" href="#">
          <img src="/assets/images/ico_move_up.png" border="0">
        </a>
      </td>
      <td><%= @Status %></td>
      <td>
        <%= link_to "Edit", edit_block_path(row)%>
        <%=  link_to 'Delete', block_path(row),:method=>"delete", :data=>{ :confirm=>'Are you sure?' } %>
      </td>
    </tr>
    <% end %>
    </tbody>
  </table>
</div>